from PyQt5 import QtCore, QtGui, QtWidgets


class LoginMainWindow(object):
    def setupUi(self, LoginMainWindow):
        LoginMainWindow.setObjectName("LoginMainWindow")
        LoginMainWindow.resize(1100, 550)
        self.centralwidget = QtWidgets.QWidget(LoginMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.main_content = QtWidgets.QWidget(self.centralwidget)
        self.main_content.setGeometry(QtCore.QRect(0, 0, 1100, 550))
        self.main_content.setObjectName("main_content")
        self.login_wapper = QtWidgets.QWidget(self.main_content)
        self.login_wapper.setGeometry(QtCore.QRect(0, 0, 1100, 550))
        self.login_wapper.setObjectName("login_wapper")
        self.login_wapper_left = QtWidgets.QWidget(self.login_wapper)
        self.login_wapper_left.setGeometry(QtCore.QRect(40, 10, 500, 500))
        self.login_wapper_left.setMinimumSize(QtCore.QSize(500, 0))
        self.login_wapper_left.setStyleSheet(
            "background: url(:/login/resources/images/login/login_bg.png) no-repeat center center;\n"
            "background-size: cover;")
        self.login_wapper_left.setObjectName("login_wapper_left")
        self.login_wapper_right = QtWidgets.QWidget(self.login_wapper)
        self.login_wapper_right.setGeometry(QtCore.QRect(540, 10, 530, 500))
        self.login_wapper_right.setStyleSheet("#login_wapper_right{ \n"
                                              "    background-color:;\n"
                                              "    background-color: rgb(204, 204, 204);\n"
                                              "}")
        self.login_wapper_right.setObjectName("login_wapper_right")
        self.layoutWidget = QtWidgets.QWidget(self.login_wapper_right)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 524, 481))
        self.layoutWidget.setObjectName("layoutWidget")
        self.VLayout_R = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.VLayout_R.setContentsMargins(0, 0, 0, 0)
        self.VLayout_R.setObjectName("VLayout_R")
        spacerItem = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.VLayout_R.addItem(spacerItem)
        self.HLayout_R1 = QtWidgets.QHBoxLayout()
        self.HLayout_R1.setObjectName("HLayout_R1")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.HLayout_R1.addItem(spacerItem1)
        self.login_title = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(22)
        self.login_title.setFont(font)
        self.login_title.setObjectName("login_title")
        self.HLayout_R1.addWidget(self.login_title)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.HLayout_R1.addItem(spacerItem2)
        self.VLayout_R.addLayout(self.HLayout_R1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.VLayout_R.addItem(spacerItem3)
        self.HLayout_R2 = QtWidgets.QHBoxLayout()
        self.HLayout_R2.setObjectName("HLayout_R2")
        spacerItem4 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.HLayout_R2.addItem(spacerItem4)
        self.GridLayout_uname = QtWidgets.QFrame(self.layoutWidget)
        self.GridLayout_uname.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.GridLayout_uname.setFrameShadow(QtWidgets.QFrame.Raised)
        self.GridLayout_uname.setObjectName("GridLayout_uname")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.GridLayout_uname)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.HL_uname = QtWidgets.QHBoxLayout()
        self.HL_uname.setObjectName("HL_uname")
        self.uname_input = QtWidgets.QLineEdit(self.GridLayout_uname)
        self.uname_input.setMinimumSize(QtCore.QSize(320, 60))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.uname_input.setFont(font)
        self.uname_input.setStyleSheet("\n"
                                       "border-radius:12px;")
        self.uname_input.setObjectName("uname_input")
        self.HL_uname.addWidget(self.uname_input)
        self.gridLayout_6.addLayout(self.HL_uname, 0, 0, 1, 1)
        self.HLayout_R2.addWidget(self.GridLayout_uname)
        spacerItem5 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.HLayout_R2.addItem(spacerItem5)
        self.VLayout_R.addLayout(self.HLayout_R2)
        spacerItem6 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.VLayout_R.addItem(spacerItem6)
        self.HLayout_R3 = QtWidgets.QHBoxLayout()
        self.HLayout_R3.setObjectName("HLayout_R3")
        spacerItem7 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.HLayout_R3.addItem(spacerItem7)
        self.GridLayout_upwd = QtWidgets.QFrame(self.layoutWidget)
        self.GridLayout_upwd.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.GridLayout_upwd.setFrameShadow(QtWidgets.QFrame.Raised)
        self.GridLayout_upwd.setObjectName("GridLayout_upwd")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.GridLayout_upwd)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.HL_upwd = QtWidgets.QHBoxLayout()
        self.HL_upwd.setObjectName("HL_upwd")
        self.upwd_input = QtWidgets.QLineEdit(self.GridLayout_upwd)
        self.upwd_input.setMinimumSize(QtCore.QSize(320, 60))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.upwd_input.setFont(font)
        self.upwd_input.setStyleSheet("\n"
                                      "border-radius:13px;")
        self.upwd_input.setText("")
        self.upwd_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.upwd_input.setObjectName("upwd_input")
        self.HL_upwd.addWidget(self.upwd_input)
        self.gridLayout_2.addLayout(self.HL_upwd, 0, 0, 1, 1)
        self.HLayout_R3.addWidget(self.GridLayout_upwd)
        spacerItem8 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.HLayout_R3.addItem(spacerItem8)
        self.VLayout_R.addLayout(self.HLayout_R3)
        spacerItem9 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.VLayout_R.addItem(spacerItem9)
        self.HLayout_R4 = QtWidgets.QHBoxLayout()
        self.HLayout_R4.setObjectName("HLayout_R4")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.HLayout_R4.addItem(spacerItem10)
        self.login_btn = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login_btn.sizePolicy().hasHeightForWidth())
        self.login_btn.setSizePolicy(sizePolicy)
        self.login_btn.setMinimumSize(QtCore.QSize(330, 60))
        self.login_btn.setMaximumSize(QtCore.QSize(330, 60))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.login_btn.setFont(font)
        self.login_btn.setStyleSheet("\n"
                                     "border-radius:13px;\n"
                                     "background-color: rgb(95, 179, 76);\n"
                                     "color:white;")
        self.login_btn.setObjectName("login_btn")
        self.HLayout_R4.addWidget(self.login_btn)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.HLayout_R4.addItem(spacerItem11)
        self.VLayout_R.addLayout(self.HLayout_R4)
        spacerItem12 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.VLayout_R.addItem(spacerItem12)
        LoginMainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(LoginMainWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginMainWindow)

    def retranslateUi(self, LoginMainWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginMainWindow.setWindowTitle(_translate("LoginMainWindow", "电商商品管理系统"))
        self.login_title.setText(_translate("LoginMainWindow", "LOGIN"))
        self.uname_input.setPlaceholderText(_translate("LoginMainWindow", "请输入用户名"))
        self.upwd_input.setPlaceholderText(_translate("LoginMainWindow", "请输入密码"))
        self.login_btn.setText(_translate("LoginMainWindow", "登        陆"))


import resources.qrc.login_rc
